### ISSUE TITLE
Related to Radar example 

### ISSUE THREAD

**Issue by LauraLaureus** [adamgreen/MiP-Capi#2]
Hi!
I'm making a project about draw a map using OpenGL and MipCapi using the infrared information of Mip. I developed my own code to get radar information based on api, but it didn't work so I run the Radar.c code but It didn't work.
At that point I thought my Mip was broken however it moves properly around my room in the yellow mode. 
I think that radar parameter in function mipGetLatestRadarNotification(pMiP, &radar) has never been changed.

My own testing code:
`
    while (1) {
        glutCheckLoop(); //OpenGL
        result = mipGetLatestRadarNotification(pMiP, &radar);

```
    switch (radar.radar) {
        case MIP_RADAR_0CM_10CM:
            printf("Distance: less than 10 cm\n");
            break;
        case MIP_RADAR_10CM_30CM:
            printf("Distance: less than 30 cm but more than 10 cm\n");
            break;

        default:
            printf("Distance: unknown\n");
            break;
    }


}`
```

It always shows unknown.
Could you fix that or tell me what I'm doing wrong?

**Comment by adamgreen** [comment]
I just tried running a clean build of the Radar sample on my MacBook Air and it worked as expected.  The program does nothing after connecting and then when I place my hand close to MiP's face, the program shuts down gracefully.  Is this not what happens on your machine?  

I did notice that MiP doesn't seem to send Radar notifications unless he is actively balancing.  If you have him laying back on the kickstand then no notifications get sent.  

Your code above looks correct to me as long as you have a previous call to mipSetGestureRadarMode(pMiP, MIP_RADAR) earlier in your code somewhere.

**Comment by LauraLaureus** [comment]
It was laying back.  >.<
Thanks for the fast reply!

**Comment by adamgreen** [comment]
I updated the documentation in commit 30bba0e to call this out.  Thanks for bringing it to my attention.  I might have known about this when I implemented/tested the code last year but I had since forgotten.

**Comment by adamgreen** [comment]
PS: Sounds like you are working on a cool project!  I used the radar mode to get my MiP to follow the wall around the room we use for our local hobby robotics meetings. The code I used can be found [here](https://github.com/adamgreen/MiP/tree/master/OSX_ConsoleSample)

**Comment by LauraLaureus** [comment]
Your project remember me to this one I did for a uni subject last year (https://www.facebook.com/laura.delpinodiaz/videos/742197932545100/) The Lego NXT has to follow something and keep the distance. I'll take a look to your code :).

**Comment by adamgreen** [comment]
That looks like a pretty cool Lego project.
